assignment2/Group21PROYECT/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get '/Home', to: 'static_pages#Home'
  root 'static_pages#Home'
  resources :boards do 
    resources :states
  end
  resources :states
  resources :tasks
  resources :users
  resources :teams do
    resources :team_memberships, only: [:new, :create, :destroy]
  end
  resources :team_memberships
end

assignment2/Group21PROYECT/app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    belongs_to :asignee_task
    belongs_to :state

    validates :title, presence: { message: "This field can't be blank" }
    validates :priority, presence:{ message: "Your task needs a priority level"}
    validates :user_id, presence:{ message: "Your task needs an associated User"}
    validates :state_id, presence:{ message: "Your task needs to be associated to a State"}
    validates :asignee_task_id, presence:{ message: "Your task needs an Assignee Id"}

    before_validation :normalize_title
    private
        def normalize_title
            self.title = title.downcase.titleize
        end
 end

assignment2/Group21PROYECT/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user!
    def index
        @tasks = Task.all
    end

    def show
        @task = Task.find(params['id'])
    end

    def new
        if params[:state_id].present?
            @state = State.find(params[:state_id])
            @task = @state.tasks.build
        else
		    @task = Task.new
        end
	end

    def create  
		@task = Task.new(task_params)
        asignee = AsigneeTask.new(user_id: task_params[:user_id])
        @board = @task.state.board_id
        if asignee.save
            respond_to do |format|
                if @task.save
                    format.html { redirect_to board_path(@board), notice: "Task was successfully created." }
                    format.json { render :show, status: :created, location: @task }
                else
                    format.html { render :new, status: :unprocessable_entity }
                    format.json { render json: @task.errors, status: :unprocessable_entity }
                end
            end
        end
	end

    def edit
		@task = Task.find(params[:id])
	end

    def update
		@task = Task.find(params[:id])
        @board = @task.state.board_id
		if @task.update task_params
				redirect_to board_path(@board)
		else
				render :edit
		end
	end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy
    
        redirect_to tasks_path, :notice => "The task was deleted"
    end

    def task_params
		params.require(:task).permit(:title, :state_id, :description, :priority, :custom_attributes, :status, :user_id, :asignee_task_id)
	end
end

assignment2/Group21PROYECT/app/views/tasks/_form.html.erb
<div class="container-l" style='margin: 30px'>
    <%= form_with(model: @task) do |f| %>
        <div class="form-group mb-3">
            <%= f.label :title %>
            <%= f.text_area :title, class: "form-control", required: true %>
        </div>

        <div class="form-group mb-3">
            <%= f.label :description %>
            <%= f.text_area :description, class: "form-control", required: true %>
        </div>

        <div class="form-group mb-3">
            <%= f.label :priority %>
            <%= f.collection_select :priority, [['LOW','LOW'], ['MEDIUM','MEDIUM'], ['HIGH','HIGH']], :first, :last, {prompt: "Select a Priority Level"},class: "form-control", required: true %>
        </div>

        <div class="form-group mb-3">
            <%= f.label :custom_attributes %>
            <%= f.text_area :custom_attributes, class: "form-control"%>
        </div>

        <div class="form-group mb-3">
            <% if user_signed_in? %>
                <%= f.hidden_field :user_id, value: current_user.id %>
            <% else %>
                <%= f.label :Informer %>
                <%= f.collection_select :user_id, User.all, :id, :name, {prompt: "Select an Informer"}, {class: "form-control"} %>
            <% end %>
        </div>

        <div class="form-group mb-3">
                <%= f.label :Asignee %>
                <% asignees = [] %>
                <% asignee_names = [] %>
                <% UserToBoard.where(user_id:current_user.id).each do |usertoboard| %>
                    <% UserToBoard.all.each do |usertoboard2| %>
                        <% if usertoboard.board_id == usertoboard2.board_id %>
                            <% unless asignee_names.include?(usertoboard2.user.name) %>
                                <% asignee_names << User.find(usertoboard2.user_id).name %>
                                <% asignees << User.find(usertoboard2.user_id) %>
                            <% end %>
                        <% end %>
                    <% end %>
                <% end %>
                <%= f.collection_select :asignee_task_id, asignees, :id, :name, {prompt: "Select an Assignee"}, {class: "form-control"} %>
        </div>
        
        <% if @state.present? %>
            <%= f.hidden_field :state_id, value: @state.id%>
        <% else %>
            <div class="form-group mb-3">
                <% if @boards.present? %>
                    <%= f.hidden_field :state_id, value: @state.id%>
                <% else %>
                    <%= f.label :state_id %>
                    <% boards = [] %>
                    <% UserToBoard.where(user_id:current_user.id).each do |usertoboard| %>
                        <% UserToBoard.all.each do |usertoboard2| %>
                            <% if usertoboard.board_id == usertoboard2.board_id %>
                                <% unless asignees.include?(usertoboard2.board_id) %>
                                    <% boards << Board.find(usertoboard2.board_id) %>
                                <% end %>
                            <% end %>
                        <% end %>
                    <% end %>
                    <% states = [] %>
                    <% State.all.each do |st| %>
                        <% boards.each do |brd| %>
                            <% if st.board == brd %>
                                <% unless states.include?(st) %>
                                <% states << st %>
                                <% end %>
                            <% end %>
                        <% end %>
                    <% end %>
                    <%= f.collection_select :state_id, states, :id, :name_with_board, {prompt: "Select a State"}, {class: "form-control"} %>
                <% end %>
            </div>
        <% end %>
        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
</div>

assignment2/Group21PROYECT/app/views/tasks/edit.html.erb
<h1> Edit Your Task Here </h1>

<%= render 'form', task: @task %>

<div class="container-l" style='margin: 30px'>
<%= link_to "Back to task", tasks_path, class: "btn btn-warning"%>
</div>

assignment2/Group21PROYECT/app/views/tasks/index.html.erb
<style>
    .container {
        margin-top: 30px;
    }
    .card {
        margin-bottom: 20px;
    }
</style>
<div class="container-fluid">
    <h1 class="text-center">Welcome to your Tasks</h1>
</div>
<% if flash[:notice] %>
    <div class="container">
        <div class="alert alert-success alert-dismissible fade show">
            <%= flash[:notice] %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
<% end %>
<div class="container">
    <div class="row">
        <% tasks = current_user.tasks.or(Task.where(asignee_task_id: current_user.id)) %>
        <% tasks.each do |task| %>
            <div class="col-lg-4 col-md-6">
                <div class="card">
                    <div class="card-body">
                        <div class="card-header bg-info text-white">
                                <h5 class="card-title"><%= task.title %></h5>
                        </div>
                        <p class="card-text"><strong>State:</strong> <%= task.state.name %></p>
                        <p class="card-text"><strong>Board:</strong> <%= task.state.board.title %></p>
                        <a href="<%= task_path(task) %>" class="btn btn-info">View Task</a>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="row mt-4">
        <div class="col-12 text-center">
            <%= link_to 'Back To Homepage', root_path, class: 'btn btn-secondary mr-2' %>
            <%= link_to 'Task Creator', new_task_path, class: 'btn btn-primary' %>
        </div>
    </div>
</div>

assignment2/Group21PROYECT/app/views/tasks/new.html.erb
<% if @state.present?%>
<h1><strong><%= @state.name %></strong></h1>
  <h2>Create a new Task for this state: </h2>
  <%= render "form", task: @task %>
  <br>

  <div>
    <div class="container-l" style='margin: 30px'>
        <%= link_to "Back to tasks", tasks_path, class: "btn btn-warning" %>
    </div>
  </div>
<% else%>

<div class="container-l" style='margin: 10px'>
    <h1>Create a New Task!</h1>
</div>


<%= render "form", task: @task %>
<div class="container-l" style='margin: 10px'>
<%= link_to "Back to tasks", tasks_path, class: "btn btn-info"%>
</div>


<% end %>

assignment2/Group21PROYECT/app/views/tasks/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-header bg-primary text-white">
      <h1 class="card-title">Board Title: <%= @task.state.board.title %></h1>
      <h1 class="card-title">State Name: <%= @task.state.name %></h1>
    </div>
    <div class="card-body">
      <h2 class="card-subtitle mb-2 text-muted">Task Title: <%= @task.title %></h2>
      <h2 class="card-subtitle mb-2 text-muted">Task Informer ID: <%= @task.user_id %> | Name: <%= @task.user.name %> </h2>
      <h2 class="card-subtitle mb-2 text-muted">Task Assignee ID: <%= @task.asignee_task_id %> | Name: <%= @task.asignee_task.user.name %></h2>
      <h2 class="card-subtitle mb-2 text-muted">Task Priority: <%= @task.priority %></h2>
      <%= link_to 'Back to Tasks', tasks_path, class: 'btn btn-warning mt-3' %>
      <% if current_user.id == @task.user_id or current_user.id == @task.asignee_task_id %>
        <%= link_to 'Task Editor', edit_task_path, class: 'btn btn-primary mt-3' %>
        <%= link_to 'Destroy Task', @task, method: :delete, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger mt-3' %>
      <% else %>
        <div class="card-body d-flex justify-content-center align-items-center centered-message">
          <p><strong>You are not authorized to delete or edit this task</strong></p>
        </div>
      <% end %>
    </div>
    <%= link_to 'Back to State', state_path(@task.state), class: 'btn btn-light mt-3' %>
  </div>
</div>