assignment2/Group21PROYECT/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get '/Home', to: 'static_pages#Home'
  root 'static_pages#Home'
  resources :boards do 
    resources :states
  end
  resources :states
  resources :tasks
  resources :users
  resources :teams do
    resources :team_memberships, only: [:new, :create, :destroy]
  end
  resources :team_memberships
end

assignment2/Group21PROYECT/app/models/board.rb
class Board < ApplicationRecord
    has_many :states, dependent: :destroy
    belongs_to :team

    validates :title, presence: { message: "You have to fill in your board title!" }
    validates :description, presence: { message: "You have put a descritpion for your board!" }

    after_create :default_states
    before_validation :normalize_title
    private
        def normalize_title
            self.title = title.downcase.titleize
        end

        def default_states
            states.create([{name: 'TODO'}, {name: 'WIP'}, {name: 'DONE'}])
        end
end

assignment2/Group21PROYECT/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :authenticate_user!, only: %i[ show new create edit update destroy ]
    def index
        @boards = Board.all
        #@state = State.all
    end

    def show
        @board = Board.find(params['id'])
        @states = @board.states
        @tasks = []
        @states.each do |state| 
            @tasks << state.tasks
        end
    end

    def new
		@board = Board.new
	end

    def create  
		@board = Board.new(board_params)
		if @board.save!
            flash[:notice] = 'Board was successfully created.'
			redirect_to boards_path
		else
            flash[:alert] = 'There was an error creating the board.'
			render :new
		end
	end

    def edit
		@board = Board.find(params[:id])
	end

    def update
		@board = Board.find(params[:id])
		if @board.update board_params
            flash[:notice] = 'Board was successfully updated.'
			redirect_to boards_path
		else
            flash[:alert] = 'There was an error updating the board.'
			render :edit
		end
	end

    def destroy
        @board = Board.find(params[:id])
        @board.destroy
    
        respond_to do |format|
          format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
          format.json { head :no_content }
        end
    end

    def board_params
		params.require(:board).permit(:title, :description, :user_id, :team_id)
	end
end

assignment2/Group21PROYECT/app/views/boards/_form.html.erb
<div class="container-l" style='margin: 30px'>
        <%= form_with(model: board) do |f| %>
            <div class="form-group mb-3">
                <%= f.label :title %>
                <%= f.text_area :title, class: "form-control", required: true %>
            </div>

            <div class="form-group mb-3">
                <%= f.label :description %>
                <%= f.text_area :description, class: "form-control", required: true %>
            </div>
            <div class="form-group mb-3">
                <%= f.label :team_id %>
                <%= f.collection_select :team_id, current_user.teams, :id, :name, { prompt: "Select a Team" }, class: "form-control", required: true %>
            </div>
            <div class="form-group mb-3">
            <% if user_signed_in? %>
                <%= f.hidden_field :user_id, value: current_user.id %>
            <% else %>
                <%= f.label :user_id %>
                <%= f.collection_select :user_id, User.all, :id, :name, {prompt: "Select a creator"}, {class: "form-control"} %>
            <% end %>
            </div>
            <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
</div>

assignment2/Group21PROYECT/app/views/boards/edit.html.erb
<h1> Edit Your Board Here </h1>

<%= render 'form', board: @board %>

<div class="container-l" style='margin: 30px'>
<%= link_to "Back to board", boards_path, class: "btn btn-warning"%>
</div>

assignment2/Group21PROYECT/app/views/boards/index.html.erb
<title>Boards</title>
<div class="container-fluid">
    <h1> Welcome to TrelloClone's Boards </h1>
</div>
<% if flash[:notice] %>
    <div class="container">
        <div class="alert alert-success alert-dismissible fade show">
            <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
<% end %>
<div class="container-l" style='margin: 30px'>
    <div class="container text-center">
        <table class="table table-striped-columns table-hover">
            <tr>
                <th> TITLE </th>
                <th> DESCRIPTION </th>
                <th> Board Owner </th>
                <th> Board Viewer </th>
            </tr>
            <% @boards.each do |board| %>
            <tr>
                <td><%= board.title %></td>
                <td><%= board.description %></td>
                <td><%= board.team.name %></td>
                <td><%= link_to 'View', board_path(board), class: 'card-link btn btn-success'%></td>
            </tr>
            <% end %>
        </table>
    <%= link_to 'Back To Homepage', root_path, class: 'btn btn-secondary' %>
    <%= link_to 'Board Creator', new_board_path, class: 'btn btn-primary' %>

    </div>
</div>

assignment2/Group21PROYECT/app/views/boards/new.html.erb
<div class="container-l" style='margin: 30px'>
    <h1>Create a New Board!</h1>
</div>


<%= render "form", board: @board %>
<div class="container-l" style='margin: 30px'>
<%= link_to "Back to boards", boards_path, class: "btn btn-warning"%>
</div>

assignment2/Group21PROYECT/app/views/boards/show.html.erb
<div class="container mt-5">
  <div class="text-center mb-4">
    <h1 class="display-4" style="font-family: 'Verdana';"><%= @board.title %></h1>
    <h2 class="lead" style="font-family: 'Verdana';"><%= @board.description %></h2>
  </div>
  <% unless current_user && current_user.teams.include?(@board.team) %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
      You are not authorized to modify this board! (Create, Edit or Delete)
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
  
  <div class="row">
        <% @states.each do |state| %>
        <div class="col-md-4 mb-4">
            <div class="card h-100">
            <div class="card-header bg-primary text-white">
                <h4 class="card-title" style="font-family: Verdana;"> <%= state.name %> </h4>
                <% if current_user && current_user.teams.include?(@board.team) %>
                  <a href="<%= state_path(state) %>" class="btn btn-warning">State View</a>
                  <a href="<%= new_task_path(state_id: state.id) %>" class="btn btn-light btn-block">Add Task</a>
                <% end %>
            </div>
            <div class="card-body">
                <div class="container">
                <% state.tasks.each do |task| %>
                    <div class="row mb-2">
                    <div class="col">
                        <div class="card">
                        <div class="card-body">
                            <h5 class="card-title"><%= task.title %></h5>
                            <p class="card-text"><%= task.description %></p>
                            <% if current_user && current_user.teams.include?(@board.team) %>
                              <a href="<%= task_path(task) %>" class="btn btn-primary btn-block">View Task</a>
                            <% end %>
                        </div>
                        </div>
                    </div>
                    </div>
                <% end %>
                </div>
            </div>
            </div>
        </div>
        <% end %>
  </div>
  <div class="text-center mt-4">
    <%= link_to 'Back to Boards', boards_path, class: 'btn btn-warning mx-2' %>
    <% if current_user && current_user.teams.include?(@board.team) %>
      <%= link_to 'Edit Board', edit_board_path(@board), class: 'btn btn-primary mx-2' %>
      <%= link_to 'Destroy Board', @board, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger mx-2' %>
    <% end %>
    
  </div>
</div>

<div class="container mt-5">
  <div class="card">
    <div class="card-header bg-light">
      <h4 class="mb-0">Create a New State for this Board</h4>
    </div>
    <div class="card-body">
    <% if current_user && current_user.teams.include?(@board.team) %>
      <%= link_to 'State Creator', new_state_path(board_id: @board.id), class: 'btn btn-light' %>
    <% else %>
    <p><strong>You are not authorized to add states to this board.</strong></p>
    <% end %>
    
    </div>
  </div>
</div>