assignment2/Group21PROYECT/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get '/Home', to: 'static_pages#Home'
  root 'static_pages#Home'
  resources :boards do 
    resources :states
  end
  resources :states
  resources :tasks
  resources :users
  resources :teams do
    resources :team_memberships, only: [:new, :create, :destroy]
  end
  resources :team_memberships
end

assignment2/Group21PROYECT/app/models/state.rb
class State < ApplicationRecord
    belongs_to :board
    has_many :tasks, dependent: :destroy
    validates :name, presence: { message: "This field can't be blank" }
    validates :board_id, presence: { message: "Your state must be associated to a board" }

    def name_with_board
        "#{name} --> #{board.title}"
    end
end

assignment2/Group21PROYECT/app/controllers/states_controller.rb
class StatesController < ApplicationController
    before_action :authenticate_user!
    def index
        @states = State.all
    end

    def show
        @state = State.find(params['id'])
        @tasks = @state.tasks
    end

    def new
        if params[:board_id].present?
            @board = Board.find(params[:board_id])
            @state = @board.states.build
        else
		    @state = State.new
        end
	end

    def create  
		@state = State.new(state_params)
        @board = @state.board_id
        respond_to do |format|
            if @state.save
                flash[:notice] = 'State was successfully created.'
                format.html { redirect_to board_path(@board), notice: "State was successfully created." }
                format.json { render :show, status: :created, location: @state }
            else
                flash[:alert] = 'There was an error creating the state.'
                render :new
            end
        end
	end

    def edit
		@state = State.find(params[:id])
	end

    def update
		@state = State.find(params[:id])
        @board = @state.board_id
		if @state.update state_params
                flash[:notice] = 'State was successfully updated.'
				redirect_to board_path(@board)
		else
                flash[:alert] = 'There was an error updating the state.'
				render :edit
		end
	end

    def destroy
        @state = State.find(params[:id])
        @state.destroy
    
        respond_to do |format|
          format.html { redirect_to states_path, notice: "State was successfully destroyed." }
          format.json { head :no_content }
        end
    end

    def state_params
		params.require(:state).permit(:name, :board_id)
	end
end

assignment2/Group21PROYECT/app/views/states/_form.html.erb
<div class="container-l" style='margin: 30px'>
    <%= form_with(model: state) do |f| %>
        <div class="form-group mb-3">
            <%= f.label :name %>
            <%= f.text_area :name, class: "form-control", required: true %>
        </div>

        <% if @board.present? %>
            <%= f.hidden_field :board_id, value: @board.id%>
        <% else %>
            <div class="form-group mb-3">
                <%= f.label :board_id %>
                <% boards = []%>
                <% UserToBoard.all.each do |usertoboard| %>
                    <% if current_user.id == usertoboard.user_id %>
                        <% unless boards.include?(usertoboard.board_id) %>
                            <% boards << Board.find(usertoboard.board_id) %>
                        <% end %>
                    <% end %>
                <% end %>
                <%= f.collection_select :board_id, boards, :id, :title, {prompt: "Select a board"}, {class: "form-control"} %>
                </div>
        <% end %>
        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
</div>

assignment2/Group21PROYECT/app/views/states/edit.html.erb
<h1> Edit Your State Here </h1>

<%= render 'form', state: @state %>

<div class="container-l" style='margin: 30px'>
<%= link_to "Back to states", states_path, class: "btn btn-warning"%>
</div>

assignment2/Group21PROYECT/app/views/states/index.html.erb
<style>
    .container {
        margin-top: 30px;
    }
    .card {
        margin-bottom: 20px;
    }
</style>
<body>
    <div class="container-fluid">
        <h1 class="text-center">Welcome to Your Board's States</h1>
    </div>
    <% if flash[:notice] %>
        <div class="container">
        <div class="alert alert-success alert-dismissible fade show">
            <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
  </div>
    <% end %>
    <div class="container" style="">
        <div class="row">
            <% @states.each do |state| %>
                <div class="col-lg-4 col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-header bg-warning text-black">
                                <h5 class="card-title"><%= state.name %></h5>
                            </div>
                            <p class="card-text">Board: <%= state.board.title %></p>
                            <a href="<%= state_path(state) %>" class="btn btn-warning">View</a>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="row mt-4">
            <div class="col-12 text-center">
                <%= link_to 'Back to Homepage', root_path, class: 'btn btn-secondary mr-2' %>
                <%= link_to 'State Creator', new_state_path, class: 'btn btn-primary' %>
            </div>
        </div>
    </div>
</body>

assignment2/Group21PROYECT/app/views/states/new.html.erb
<% if @board.present?%>
<h1><strong><%= @board.title %></strong></h1>
  <h2>Create a new State for this board: </h2>
  <%= render "form", state: @state %>
  <br>

  <div>
    <div class="container-l" style='margin: 30px'>
        <%= link_to "Back to states", states_path, class: "btn btn-warning" %>
    </div>
  </div>
<% else%>

<div class="container-l" style='margin: 30px'>
    <h1>Create a New State!</h1>
</div>


<%= render "form", state: @state %>
<div class="container-l" style='margin: 30px'>
<%= link_to "Back to states", states_path, class: "btn btn-warning"%>
</div>


<% end %>

assignment2/Group21PROYECT/app/views/states/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-header bg-primary text-white">
      <h1 class="card-title">Board Title: <%= @state.board.title %></h1>
    </div>
    <div class="card-body">
      <h2 class="card-subtitle mb-2 text-muted">State Name: <%= @state.name %></h2>
      <%= link_to 'Back to States', states_path, class: 'btn btn-warning mt-3' %>

      <% boolean = 0 %>
      <% @all_board.each do |board| %>
        <% if current_user.id == board.user_id %>
          <% boolean = 1 %>
          <% break %>
        <% end %>
      <% end %>
      <% if boolean == 1 %>
        <%= link_to 'State Editor', edit_state_path, class: 'btn btn-primary mt-3' %>
        <%= link_to 'Destroy State', @state, method: :delete, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger mt-3' %>
        <%= link_to 'Create Tasks', new_task_path(state_id: @state.id), class: 'btn btn-success mt-3' %>
      <% else %>
        <div class="card-body d-flex justify-content-center align-items-center centered-message">
          <p><strong>You are not authorized to delete or edit this state</strong></p>
        </div>
      <% end %>
    </div>
      <%= link_to 'Back to Board', board_path(@state.board), class: 'btn btn-light mt-3' %>
  </div>
</div>