assignment2/Group21PROYECT/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get '/Home', to: 'static_pages#Home'
  root 'static_pages#Home'
  resources :boards do 
    resources :states
  end
  resources :states
  resources :tasks
  resources :users
  resources :teams do
    resources :team_memberships, only: [:new, :create, :destroy]
  end
  resources :team_memberships
end

assignment2/Group21PROYECT/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :team_memberships, dependent: :destroy
    has_many :teams, through: :team_memberships
    has_many :tasks, dependent: :destroy
    has_many :asignee_tasks, dependent: :destroy
    
    validates :name, presence: { message: "You have to fill in your username!" }
    validates :email, presence: { message: "You have to fill in your email!" }, uniqueness: { message: "This email is already in use" }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Invalid email format" }
    validates :password, presence: { message: "You have to fill in your password!" }, length: { minimum: 6, message: "Password must be at least 6 characters long" }

    before_validation :downcase_email
    before_validation :normalize_name
    private
        def downcase_email
            self.email = email.downcase
        end
        def normalize_name
            self.name = name.downcase.titleize
        end
end

assignment2/Group21PROYECT/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:show, :index]
    def index
        @users = User.all
    end
    def show
        @user = User.find(params['id'])
        @tasks = @user.tasks
        @teams = @user.teams
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        
        respond_to do |format|
          format.html { redirect_to users_url, notice: "user was successfully destroyed." }
          format.json { head :no_content }
        end
    end
    def user_params
		params.require(:user).permit(:name, :email, :password)
	end
end

assignment2/Group21PROYECT/app/views/users/index.html.erb
<title>Users</title>
<div class="container-fluid">
    <h1> Welcome to our Users</h1>
</div>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>
<div class="container-l" style='margin: 30px'>
    <div class="container text-center">
        <table class="table table-striped-columns table-hover">
            <tr>
                <th> NAME </th>
                <th> EMAIL </th>
                <th> View User </th>
            </tr>
            <% @users.each do |user| %>
            <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><a href="<%= user_path(user) %>" class="btn btn-success">View</a></td>
            </tr>
            <% end %>
        </table>
    <%= link_to 'Back To Homepage', root_path, class: 'btn btn-secondary' %>
    <!-- <%= link_to 'User Creator', new_user_path, class: 'btn btn-primary' %> -->

    </div>
</div>

assignment2/Group21PROYECT/app/views/users/show.html.erb
<div class="container mt-3">
  <div class="card">
    <div class="card-header bg-primary text-white">
      <h1 class="card-title">User Name: <%= @user.name %></h1>
    </div>
    <div class="card-body">
      <h2 class="card-title">User E-mail: <%= @user.email %></h2>

      <div class="mt-4">
        <h3>Teams</h3>
        <ul class="list-group">
          <% @teams.each do |team| %>
            <li class="list-group-item">
              <strong><%= link_to team.name, team_path(team) %></strong>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="mt-4">
        <h3>Tasks</h3>
        <ul class="list-group">
          <% @tasks.each do |task| %>
            <li class="list-group-item">
              <strong><%= link_to task.title, task_path(task) %></strong> - <%= task.description %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <% if current_user == @user %>
      <%= link_to 'Destroy User', @user, method: :delete, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger mt-3' %>
      <%= link_to 'Edit User', edit_user_registration_path, class: 'btn btn-info mt-3' %>
    <% else %>
      <div class="card-body d-flex justify-content-center align-items-center centered-message">
        <p><strong>You are not authorized to delete or edit this user</strong></p>
      </div>
    <% end %>
  </div>
</div>